(define (problem p_0_25)
  (:domain llibresnivell0)

  (:objects
	  A0  A1  A2  A3  A4  A5  A6  A7  A8  A9  B0  B1  B2  B3  B4  B5  B6  B7  B8  B9  C0  C1  C2  C3  C4
	)
  (:init
    (delCataleg A0)
    (delCataleg A1)
    (delCataleg A2)
    (delCataleg A3)
    (delCataleg A4)
    (delCataleg A5)
    (delCataleg A6)
    (delCataleg A7)
    (delCataleg A8)
    (delCataleg A9)
    (delCataleg B0)
    (delCataleg B1)
    (delCataleg B2)
    (delCataleg B3)
    (delCataleg B4)
    (delCataleg B5)
    (delCataleg B6)
    (delCataleg B7)
    (delCataleg B8)
    (delCataleg B9)
    (delCataleg C0)
    (delCataleg C1)
    (delCataleg C2)
    (delCataleg C3)
    (delCataleg C4)

    (predecessor B9 C2)
    (predecessor A8 B3)
    (predecessor A5 A6)
    (predecessor B0 B9)
    (predecessor B4 C4)
    (predecessor A2 B3)
    (predecessor B7 C2)
    (predecessor C2 C3)
    (predecessor C3 C4)
    (predecessor A5 C0)
    (predecessor A5 B1)
    (predecessor A7 A9)
    (predecessor A3 A8)
    (predecessor B6 B8)

  )
  (:goal (forall (?ll) (imply (not (exists (?ll2) (predecessor ?ll ?ll2))) (llegit ?ll))))
)