(define (problem p_1_70)
  (:domain llibresnivell1)

  (:objects
	  A0  A1  A2  A3  A4  A5  A6  A7  A8  A9  B0  B1  B2  B3  B4  B5  B6  B7  B8  B9  C0  C1  C2  C3  C4  C5  C6  C7  C8  C9  D0  D1  D2  D3  D4  D5  D6  D7  D8  D9  E0  E1  E2  E3  E4  E5  E6  E7  E8  E9  F0  F1  F2  F3  F4  F5  F6  F7  F8  F9  G0  G1  G2  G3  G4  G5  G6  G7  G8  G9
	)
  (:init
    (delCataleg A0)
    (delCataleg A1)
    (delCataleg A2)
    (delCataleg A3)
    (delCataleg A4)
    (delCataleg A5)
    (delCataleg A6)
    (delCataleg A7)
    (delCataleg A8)
    (delCataleg A9)
    (delCataleg B0)
    (delCataleg B1)
    (delCataleg B2)
    (delCataleg B3)
    (delCataleg B4)
    (delCataleg B5)
    (delCataleg B6)
    (delCataleg B7)
    (delCataleg B8)
    (delCataleg B9)
    (delCataleg C0)
    (delCataleg C1)
    (delCataleg C2)
    (delCataleg C3)
    (delCataleg C4)
    (delCataleg C5)
    (delCataleg C6)
    (delCataleg C7)
    (delCataleg C8)
    (delCataleg C9)
    (delCataleg D0)
    (delCataleg D1)
    (delCataleg D2)
    (delCataleg D3)
    (delCataleg D4)
    (delCataleg D5)
    (delCataleg D6)
    (delCataleg D7)
    (delCataleg D8)
    (delCataleg D9)
    (delCataleg E0)
    (delCataleg E1)
    (delCataleg E2)
    (delCataleg E3)
    (delCataleg E4)
    (delCataleg E5)
    (delCataleg E6)
    (delCataleg E7)
    (delCataleg E8)
    (delCataleg E9)
    (delCataleg F0)
    (delCataleg F1)
    (delCataleg F2)
    (delCataleg F3)
    (delCataleg F4)
    (delCataleg F5)
    (delCataleg F6)
    (delCataleg F7)
    (delCataleg F8)
    (delCataleg F9)
    (delCataleg G0)
    (delCataleg G1)
    (delCataleg G2)
    (delCataleg G3)
    (delCataleg G4)
    (delCataleg G5)
    (delCataleg G6)
    (delCataleg G7)
    (delCataleg G8)
    (delCataleg G9)

    (predecessor E7 F6)
    (predecessor B7 C9)
    (predecessor A0 E4)
    (predecessor G4 G8)
    (predecessor B0 D2)
    (predecessor A5 F4)
    (predecessor C1 G7)
    (predecessor F7 G9)
    (predecessor F4 F7)
    (predecessor C1 D7)
    (predecessor A6 B4)
    (predecessor B6 E9)
    (predecessor A8 F8)
    (predecessor E9 F3)
    (predecessor D7 F1)
    (predecessor C8 F5)
    (predecessor B1 G1)
    (predecessor D4 E8)
    (predecessor F0 F9)
    (predecessor E3 G9)
    (predecessor A5 D1)
    (predecessor A0 F3)
    (predecessor A7 G5)
    (predecessor E8 G4)
    (predecessor B7 B9)
    (predecessor D0 F8)
    (predecessor B4 F3)
    (predecessor A0 B6)
    (predecessor C5 D8)
    (predecessor E2 E3)
    (predecessor B0 B9)
    (predecessor A2 G7)
    (predecessor B0 E7)
    (predecessor G3 G8)
    (predecessor C5 F2)
    (predecessor A8 D4)
    (predecessor C4 G5)
    (predecessor B1 F6)
    (predecessor B8 D0)
    (predecessor A5 B2)
    (predecessor D4 E4)
    (predecessor D4 D7)
    (predecessor B5 G1)
    (predecessor F1 F9)
    (predecessor C0 G0)
    (predecessor G4 G5)
    (predecessor E6 G8)
    (predecessor G6 G9)
    (predecessor B1 G7)
    (predecessor E4 E8)
    (predecessor E6 G1)
    (predecessor C6 F2)
    (predecessor C5 G2)
    (predecessor A2 F1)
    (predecessor F5 F7)
    (predecessor C7 E2)
    (predecessor F6 G1)
    (predecessor E1 G8)
    (predecessor B1 D1)

    (= (MesSeguent) 0)
  )
  (:goal (forall (?ll) (imply (not (exists (?ll2) (predecessor ?ll ?ll2))) (llegit ?ll))))
)