(define (problem p_2_65)
  (:domain llibresnivell2)

  (:objects
	  A0  A1  A2  A3  A4  A5  A6  A7  A8  A9  B0  B1  B2  B3  B4  B5  B6  B7  B8  B9  C0  C1  C2  C3  C4  C5  C6  C7  C8  C9  D0  D1  D2  D3  D4  D5  D6  D7  D8  D9  E0  E1  E2  E3  E4  E5  E6  E7  E8  E9  F0  F1  F2  F3  F4  F5  F6  F7  F8  F9  G0  G1  G2  G3  G4
	)
  (:init
    (delCataleg A0)
    (delCataleg A1)
    (delCataleg A2)
    (delCataleg A3)
    (delCataleg A4)
    (delCataleg A5)
    (delCataleg A6)
    (delCataleg A7)
    (delCataleg A8)
    (delCataleg A9)
    (delCataleg B0)
    (delCataleg B1)
    (delCataleg B2)
    (delCataleg B3)
    (delCataleg B4)
    (delCataleg B5)
    (delCataleg B6)
    (delCataleg B7)
    (delCataleg B8)
    (delCataleg B9)
    (delCataleg C0)
    (delCataleg C1)
    (delCataleg C2)
    (delCataleg C3)
    (delCataleg C4)
    (delCataleg C5)
    (delCataleg C6)
    (delCataleg C7)
    (delCataleg C8)
    (delCataleg C9)
    (delCataleg D0)
    (delCataleg D1)
    (delCataleg D2)
    (delCataleg D3)
    (delCataleg D4)
    (delCataleg D5)
    (delCataleg D6)
    (delCataleg D7)
    (delCataleg D8)
    (delCataleg D9)
    (delCataleg E0)
    (delCataleg E1)
    (delCataleg E2)
    (delCataleg E3)
    (delCataleg E4)
    (delCataleg E5)
    (delCataleg E6)
    (delCataleg E7)
    (delCataleg E8)
    (delCataleg E9)
    (delCataleg F0)
    (delCataleg F1)
    (delCataleg F2)
    (delCataleg F3)
    (delCataleg F4)
    (delCataleg F5)
    (delCataleg F6)
    (delCataleg F7)
    (delCataleg F8)
    (delCataleg F9)
    (delCataleg G0)
    (delCataleg G1)
    (delCataleg G2)
    (delCataleg G3)
    (delCataleg G4)

    (predecessor E7 F6)
    (predecessor B7 C9)
    (predecessor A0 E4)
    (predecessor F9 G4)
    (predecessor B0 D2)
    (predecessor A5 F2)
    (predecessor E8 F4)
    (predecessor F7 G3)
    (predecessor F4 F7)
    (predecessor C1 D7)
    (predecessor A6 B4)
    (predecessor B6 E9)
    (predecessor A8 F8)
    (predecessor E9 G2)
    (predecessor B3 D2)
    (predecessor C6 E1)
    (predecessor F3 F5)
    (predecessor D4 G4)
    (predecessor C6 F2)
    (predecessor D5 E6)
    (predecessor A5 B8)
    (predecessor A0 F3)
    (predecessor A7 D2)
    (predecessor G2 G3)
    (predecessor A3 B9)
    (predecessor F4 F6)
    (predecessor A0 B6)
    (predecessor C5 D8)
    (predecessor E2 E3)
    (predecessor B0 B9)
    (predecessor A2 D5)
    (predecessor B0 E7)
    (predecessor G3 G4)
    (predecessor F0 F4)
    (predecessor B1 F6)
    (predecessor B8 D0)
    (predecessor A5 A9)
    (predecessor D4 F2)
    (predecessor B9 D7)
    (predecessor A4 B2)
    (predecessor F1 F5)
    (predecessor C0 G0)
    (predecessor A5 F3)
    (predecessor E6 G3)
    (predecessor B1 D4)
    (predecessor B4 F2)
    (predecessor E6 G1)
    (predecessor C5 G2)
    (predecessor A2 C7)
    (predecessor F5 F7)
    (predecessor C7 E2)
    (predecessor F6 G1)
    (predecessor E1 E4)
    (predecessor D9 G0)
    (predecessor D6 E0)
    (predecessor A7 A9)
    (predecessor E8 G2)

    (parallel E4 F2)
    (parallel A8 D6)
    (parallel C9 D6)
    (parallel F1 G0)
    (parallel E7 F9)
    (parallel B7 G0)
    (parallel D7 E3)
    (parallel D3 D4)

    (= (MesSeguent) 0)
  )
  (:goal (forall (?ll) (imply (not (exists (?ll2) (predecessor ?ll ?ll2))) (llegit ?ll))))
)