(define (problem p_3_25)
  (:domain llibresnivell3)

  (:objects
	  A0  A1  A2  A3  A4  A5  A6  A7  A8  A9  B0  B1  B2  B3  B4  B5  B6  B7  B8  B9  C0  C1  C2  C3  C4
	)
  (:init
    (delCataleg A0)
    (delCataleg A1)
    (delCataleg A2)
    (delCataleg A3)
    (delCataleg A4)
    (delCataleg A5)
    (delCataleg A6)
    (delCataleg A7)
    (delCataleg A8)
    (delCataleg A9)
    (delCataleg B0)
    (delCataleg B1)
    (delCataleg B2)
    (delCataleg B3)
    (delCataleg B4)
    (delCataleg B5)
    (delCataleg B6)
    (delCataleg B7)
    (delCataleg B8)
    (delCataleg B9)
    (delCataleg C0)
    (delCataleg C1)
    (delCataleg C2)
    (delCataleg C3)
    (delCataleg C4)

    (= (PaginesLlibre A0) 310)
    (= (PaginesLlibre A1) 356)
    (= (PaginesLlibre A2) 194)
    (= (PaginesLlibre A3) 416)
    (= (PaginesLlibre A4) 388)
    (= (PaginesLlibre A5) 263)
    (= (PaginesLlibre A6) 341)
    (= (PaginesLlibre A7) 425)
    (= (PaginesLlibre A8) 235)
    (= (PaginesLlibre A9) 219)
    (= (PaginesLlibre B0) 499)
    (= (PaginesLlibre B1) 304)
    (= (PaginesLlibre B2) 263)
    (= (PaginesLlibre B3) 146)
    (= (PaginesLlibre B4) 274)
    (= (PaginesLlibre B5) 183)
    (= (PaginesLlibre B6) 348)
    (= (PaginesLlibre B7) 541)
    (= (PaginesLlibre B8) 173)
    (= (PaginesLlibre B9) 314)
    (= (PaginesLlibre C0) 294)
    (= (PaginesLlibre C1) 358)
    (= (PaginesLlibre C2) 345)
    (= (PaginesLlibre C3) 162)
    (= (PaginesLlibre C4) 352)

    (predecessor C3 C4)
    (predecessor A3 B6)
    (predecessor A7 B3)
    (predecessor B9 C4)
    (predecessor A1 B3)
    (predecessor C1 C4)
    (predecessor B8 C3)
    (predecessor C2 C3)
    (predecessor B1 B3)

    (parallel B1 B9)
    (parallel A6 B9)
    (parallel A6 A7)
    (parallel B2 C2)

    (= (MesSeguent) 0)
    (= (PaginesMes) 0)
  )
  (:goal (forall (?ll) (imply (not (exists (?ll2) (predecessor ?ll ?ll2))) (llegit ?ll))))
)