(define (problem p_3_55)
  (:domain llibresnivell3)

  (:objects
	  A0  A1  A2  A3  A4  A5  A6  A7  A8  A9  B0  B1  B2  B3  B4  B5  B6  B7  B8  B9  C0  C1  C2  C3  C4  C5  C6  C7  C8  C9  D0  D1  D2  D3  D4  D5  D6  D7  D8  D9  E0  E1  E2  E3  E4  E5  E6  E7  E8  E9  F0  F1  F2  F3  F4
	)
  (:init
    (delCataleg A0)
    (delCataleg A1)
    (delCataleg A2)
    (delCataleg A3)
    (delCataleg A4)
    (delCataleg A5)
    (delCataleg A6)
    (delCataleg A7)
    (delCataleg A8)
    (delCataleg A9)
    (delCataleg B0)
    (delCataleg B1)
    (delCataleg B2)
    (delCataleg B3)
    (delCataleg B4)
    (delCataleg B5)
    (delCataleg B6)
    (delCataleg B7)
    (delCataleg B8)
    (delCataleg B9)
    (delCataleg C0)
    (delCataleg C1)
    (delCataleg C2)
    (delCataleg C3)
    (delCataleg C4)
    (delCataleg C5)
    (delCataleg C6)
    (delCataleg C7)
    (delCataleg C8)
    (delCataleg C9)
    (delCataleg D0)
    (delCataleg D1)
    (delCataleg D2)
    (delCataleg D3)
    (delCataleg D4)
    (delCataleg D5)
    (delCataleg D6)
    (delCataleg D7)
    (delCataleg D8)
    (delCataleg D9)
    (delCataleg E0)
    (delCataleg E1)
    (delCataleg E2)
    (delCataleg E3)
    (delCataleg E4)
    (delCataleg E5)
    (delCataleg E6)
    (delCataleg E7)
    (delCataleg E8)
    (delCataleg E9)
    (delCataleg F0)
    (delCataleg F1)
    (delCataleg F2)
    (delCataleg F3)
    (delCataleg F4)

    (= (PaginesLlibre A0) 310)
    (= (PaginesLlibre A1) 356)
    (= (PaginesLlibre A2) 194)
    (= (PaginesLlibre A3) 416)
    (= (PaginesLlibre A4) 388)
    (= (PaginesLlibre A5) 263)
    (= (PaginesLlibre A6) 341)
    (= (PaginesLlibre A7) 425)
    (= (PaginesLlibre A8) 235)
    (= (PaginesLlibre A9) 219)
    (= (PaginesLlibre B0) 499)
    (= (PaginesLlibre B1) 304)
    (= (PaginesLlibre B2) 263)
    (= (PaginesLlibre B3) 146)
    (= (PaginesLlibre B4) 274)
    (= (PaginesLlibre B5) 183)
    (= (PaginesLlibre B6) 348)
    (= (PaginesLlibre B7) 541)
    (= (PaginesLlibre B8) 173)
    (= (PaginesLlibre B9) 314)
    (= (PaginesLlibre C0) 294)
    (= (PaginesLlibre C1) 358)
    (= (PaginesLlibre C2) 345)
    (= (PaginesLlibre C3) 162)
    (= (PaginesLlibre C4) 352)
    (= (PaginesLlibre C5) 203)
    (= (PaginesLlibre C6) 197)
    (= (PaginesLlibre C7) 432)
    (= (PaginesLlibre C8) 397)
    (= (PaginesLlibre C9) 149)
    (= (PaginesLlibre D0) 358)
    (= (PaginesLlibre D1) 340)
    (= (PaginesLlibre D2) 438)
    (= (PaginesLlibre D3) 304)
    (= (PaginesLlibre D4) 305)
    (= (PaginesLlibre D5) 150)
    (= (PaginesLlibre D6) 491)
    (= (PaginesLlibre D7) 391)
    (= (PaginesLlibre D8) 429)
    (= (PaginesLlibre D9) 289)
    (= (PaginesLlibre E0) 478)
    (= (PaginesLlibre E1) 371)
    (= (PaginesLlibre E2) 444)
    (= (PaginesLlibre E3) 232)
    (= (PaginesLlibre E4) 287)
    (= (PaginesLlibre E5) 339)
    (= (PaginesLlibre E6) 170)
    (= (PaginesLlibre E7) 373)
    (= (PaginesLlibre E8) 288)
    (= (PaginesLlibre E9) 433)
    (= (PaginesLlibre F0) 444)
    (= (PaginesLlibre F1) 617)
    (= (PaginesLlibre F2) 541)
    (= (PaginesLlibre F3) 330)
    (= (PaginesLlibre F4) 356)

    (predecessor F0 F2)
    (predecessor A0 B3)
    (predecessor B1 E2)
    (predecessor C9 E8)
    (predecessor D5 F3)
    (predecessor C4 C7)
    (predecessor B1 E7)
    (predecessor D0 E9)
    (predecessor B6 F1)
    (predecessor A4 E6)
    (predecessor A1 D9)
    (predecessor D7 F1)
    (predecessor D4 E4)
    (predecessor D3 F0)
    (predecessor D4 D7)
    (predecessor E1 F1)
    (predecessor A4 F1)
    (predecessor B4 C3)
    (predecessor A6 B3)
    (predecessor E4 F2)
    (predecessor C9 D1)
    (predecessor D1 F2)
    (predecessor E6 E7)
    (predecessor E3 F3)
    (predecessor A1 C5)
    (predecessor B5 E5)
    (predecessor B4 D8)
    (predecessor F2 F4)
    (predecessor B5 B8)
    (predecessor D9 E9)
    (predecessor A5 E5)
    (predecessor A3 E7)
    (predecessor C6 E0)
    (predecessor D7 E0)
    (predecessor A5 B8)
    (predecessor A2 E1)
    (predecessor E8 F0)
    (predecessor A5 B0)
    (predecessor A1 C4)
    (predecessor D9 E7)
    (predecessor D0 D1)
    (predecessor E5 E7)
    (predecessor C1 C7)
    (predecessor F0 F3)
    (predecessor A0 D0)
    (predecessor C8 E7)
    (predecessor A9 D4)
    (predecessor D0 D5)

    (parallel C2 D7)
    (parallel C8 F3)

    (= (MesSeguent) 0)
    (= (PaginesMes) 0)
  )
  (:goal (forall (?ll) (imply (not (exists (?ll2) (predecessor ?ll ?ll2))) (llegit ?ll))))
)