(define (problem p_3_65)
  (:domain llibresnivell3)

  (:objects
	  A0  A1  A2  A3  A4  A5  A6  A7  A8  A9  B0  B1  B2  B3  B4  B5  B6  B7  B8  B9  C0  C1  C2  C3  C4  C5  C6  C7  C8  C9  D0  D1  D2  D3  D4  D5  D6  D7  D8  D9  E0  E1  E2  E3  E4  E5  E6  E7  E8  E9  F0  F1  F2  F3  F4  F5  F6  F7  F8  F9  G0  G1  G2  G3  G4
	)
  (:init
    (delCataleg A0)
    (delCataleg A1)
    (delCataleg A2)
    (delCataleg A3)
    (delCataleg A4)
    (delCataleg A5)
    (delCataleg A6)
    (delCataleg A7)
    (delCataleg A8)
    (delCataleg A9)
    (delCataleg B0)
    (delCataleg B1)
    (delCataleg B2)
    (delCataleg B3)
    (delCataleg B4)
    (delCataleg B5)
    (delCataleg B6)
    (delCataleg B7)
    (delCataleg B8)
    (delCataleg B9)
    (delCataleg C0)
    (delCataleg C1)
    (delCataleg C2)
    (delCataleg C3)
    (delCataleg C4)
    (delCataleg C5)
    (delCataleg C6)
    (delCataleg C7)
    (delCataleg C8)
    (delCataleg C9)
    (delCataleg D0)
    (delCataleg D1)
    (delCataleg D2)
    (delCataleg D3)
    (delCataleg D4)
    (delCataleg D5)
    (delCataleg D6)
    (delCataleg D7)
    (delCataleg D8)
    (delCataleg D9)
    (delCataleg E0)
    (delCataleg E1)
    (delCataleg E2)
    (delCataleg E3)
    (delCataleg E4)
    (delCataleg E5)
    (delCataleg E6)
    (delCataleg E7)
    (delCataleg E8)
    (delCataleg E9)
    (delCataleg F0)
    (delCataleg F1)
    (delCataleg F2)
    (delCataleg F3)
    (delCataleg F4)
    (delCataleg F5)
    (delCataleg F6)
    (delCataleg F7)
    (delCataleg F8)
    (delCataleg F9)
    (delCataleg G0)
    (delCataleg G1)
    (delCataleg G2)
    (delCataleg G3)
    (delCataleg G4)

    (= (PaginesLlibre A0) 310)
    (= (PaginesLlibre A1) 356)
    (= (PaginesLlibre A2) 194)
    (= (PaginesLlibre A3) 416)
    (= (PaginesLlibre A4) 388)
    (= (PaginesLlibre A5) 263)
    (= (PaginesLlibre A6) 341)
    (= (PaginesLlibre A7) 425)
    (= (PaginesLlibre A8) 235)
    (= (PaginesLlibre A9) 219)
    (= (PaginesLlibre B0) 499)
    (= (PaginesLlibre B1) 304)
    (= (PaginesLlibre B2) 263)
    (= (PaginesLlibre B3) 146)
    (= (PaginesLlibre B4) 274)
    (= (PaginesLlibre B5) 183)
    (= (PaginesLlibre B6) 348)
    (= (PaginesLlibre B7) 541)
    (= (PaginesLlibre B8) 173)
    (= (PaginesLlibre B9) 314)
    (= (PaginesLlibre C0) 294)
    (= (PaginesLlibre C1) 358)
    (= (PaginesLlibre C2) 345)
    (= (PaginesLlibre C3) 162)
    (= (PaginesLlibre C4) 352)
    (= (PaginesLlibre C5) 203)
    (= (PaginesLlibre C6) 197)
    (= (PaginesLlibre C7) 432)
    (= (PaginesLlibre C8) 397)
    (= (PaginesLlibre C9) 149)
    (= (PaginesLlibre D0) 358)
    (= (PaginesLlibre D1) 340)
    (= (PaginesLlibre D2) 438)
    (= (PaginesLlibre D3) 304)
    (= (PaginesLlibre D4) 305)
    (= (PaginesLlibre D5) 150)
    (= (PaginesLlibre D6) 491)
    (= (PaginesLlibre D7) 391)
    (= (PaginesLlibre D8) 429)
    (= (PaginesLlibre D9) 289)
    (= (PaginesLlibre E0) 478)
    (= (PaginesLlibre E1) 371)
    (= (PaginesLlibre E2) 444)
    (= (PaginesLlibre E3) 232)
    (= (PaginesLlibre E4) 287)
    (= (PaginesLlibre E5) 339)
    (= (PaginesLlibre E6) 170)
    (= (PaginesLlibre E7) 373)
    (= (PaginesLlibre E8) 288)
    (= (PaginesLlibre E9) 433)
    (= (PaginesLlibre F0) 444)
    (= (PaginesLlibre F1) 617)
    (= (PaginesLlibre F2) 541)
    (= (PaginesLlibre F3) 330)
    (= (PaginesLlibre F4) 356)
    (= (PaginesLlibre F5) 413)
    (= (PaginesLlibre F6) 302)
    (= (PaginesLlibre F7) 294)
    (= (PaginesLlibre F8) 256)
    (= (PaginesLlibre F9) 488)
    (= (PaginesLlibre G0) 580)
    (= (PaginesLlibre G1) 334)
    (= (PaginesLlibre G2) 400)
    (= (PaginesLlibre G3) 196)
    (= (PaginesLlibre G4) 382)

    (predecessor F8 F9)
    (predecessor G2 G3)
    (predecessor A3 C7)
    (predecessor D1 G1)
    (predecessor C9 F3)
    (predecessor G3 G4)
    (predecessor A4 E4)
    (predecessor B0 F0)
    (predecessor A6 F0)
    (predecessor F2 F9)
    (predecessor A8 B4)
    (predecessor C4 C7)
    (predecessor C3 C9)
    (predecessor A8 B0)
    (predecessor E5 G1)
    (predecessor G0 G1)
    (predecessor A9 D1)
    (predecessor B0 G1)
    (predecessor E1 E2)
    (predecessor F9 G3)
    (predecessor B9 E4)
    (predecessor G1 G2)
    (predecessor B3 D6)
    (predecessor C9 F8)
    (predecessor B6 C9)
    (predecessor C8 D5)
    (predecessor B4 B8)
    (predecessor B5 C0)
    (predecessor B0 D4)
    (predecessor B3 G1)
    (predecessor A3 D3)
    (predecessor C5 E9)
    (predecessor B0 C6)
    (predecessor A0 D3)
    (predecessor C5 C6)
    (predecessor F6 G1)
    (predecessor A2 G4)
    (predecessor B3 E7)
    (predecessor F3 F4)
    (predecessor D2 G3)
    (predecessor E0 G0)
    (predecessor C8 D2)
    (predecessor D5 E0)
    (predecessor D8 E0)
    (predecessor C3 E6)
    (predecessor F1 F2)
    (predecessor D8 E2)
    (predecessor A3 C4)
    (predecessor F6 G0)
    (predecessor F3 G3)
    (predecessor E1 F7)
    (predecessor E4 F7)
    (predecessor F5 F9)
    (predecessor B0 C8)
    (predecessor D8 F3)
    (predecessor F9 G4)
    (predecessor F8 G2)
    (predecessor E9 F2)
    (predecessor E2 F5)
    (predecessor A7 C8)
    (predecessor B1 C2)
    (predecessor E0 F8)
    (predecessor A3 B6)

    (parallel E6 F1)
    (parallel B0 D2)
    (parallel F7 G2)
    (parallel E9 F3)
    (parallel E2 E5)

    (= (MesSeguent) 0)
    (= (PaginesMes) 0)
  )
  (:goal (forall (?ll) (imply (not (exists (?ll2) (predecessor ?ll ?ll2))) (llegit ?ll))))
)