(define (problem p_1_35)
  (:domain llibresnivell1)

  (:objects
	  A0  A1  A2  A3  A4  A5  A6  A7  A8  A9  B0  B1  B2  B3  B4  B5  B6  B7  B8  B9  C0  C1  C2  C3  C4  C5  C6  C7  C8  C9  D0  D1  D2  D3  D4
	)
  (:init
    (delCataleg A0)
    (delCataleg A1)
    (delCataleg A2)
    (delCataleg A3)
    (delCataleg A4)
    (delCataleg A5)
    (delCataleg A6)
    (delCataleg A7)
    (delCataleg A8)
    (delCataleg A9)
    (delCataleg B0)
    (delCataleg B1)
    (delCataleg B2)
    (delCataleg B3)
    (delCataleg B4)
    (delCataleg B5)
    (delCataleg B6)
    (delCataleg B7)
    (delCataleg B8)
    (delCataleg B9)
    (delCataleg C0)
    (delCataleg C1)
    (delCataleg C2)
    (delCataleg C3)
    (delCataleg C4)
    (delCataleg C5)
    (delCataleg C6)
    (delCataleg C7)
    (delCataleg C8)
    (delCataleg C9)
    (delCataleg D0)
    (delCataleg D1)
    (delCataleg D2)
    (delCataleg D3)
    (delCataleg D4)

    (predecessor C3 C8)
    (predecessor A8 B4)
    (predecessor A0 C2)
    (predecessor D2 D4)
    (predecessor A5 B6)
    (predecessor A2 C7)
    (predecessor B0 D3)
    (predecessor C8 D4)
    (predecessor C7 C9)
    (predecessor B0 B8)
    (predecessor A3 A7)
    (predecessor A8 C5)
    (predecessor A4 C9)
    (predecessor C4 C6)
    (predecessor B8 C5)
    (predecessor B4 C8)
    (predecessor A5 D0)
    (predecessor B7 C4)
    (predecessor C5 D0)
    (predecessor C1 D4)
    (predecessor A2 B5)
    (predecessor A0 C7)
    (predecessor A3 D2)
    (predecessor C4 D2)
    (predecessor A8 A9)
    (predecessor B5 C9)
    (predecessor A7 C7)
    (predecessor A0 A8)
    (predecessor B2 B9)
    (predecessor C1 C2)

    (= (MesSeguent) 0)
  )
  (:goal (forall (?ll) (imply (not (exists (?ll2) (predecessor ?ll ?ll2))) (llegit ?ll))))
)