(define (problem p_3_75)
  (:domain llibresnivell3)

  (:objects
	  A0  A1  A2  A3  A4  A5  A6  A7  A8  A9  B0  B1  B2  B3  B4  B5  B6  B7  B8  B9  C0  C1  C2  C3  C4  C5  C6  C7  C8  C9  D0  D1  D2  D3  D4  D5  D6  D7  D8  D9  E0  E1  E2  E3  E4  E5  E6  E7  E8  E9  F0  F1  F2  F3  F4  F5  F6  F7  F8  F9  G0  G1  G2  G3  G4  G5  G6  G7  G8  G9  H0  H1  H2  H3  H4
	)
  (:init
    (delCataleg A0)
    (delCataleg A1)
    (delCataleg A2)
    (delCataleg A3)
    (delCataleg A4)
    (delCataleg A5)
    (delCataleg A6)
    (delCataleg A7)
    (delCataleg A8)
    (delCataleg A9)
    (delCataleg B0)
    (delCataleg B1)
    (delCataleg B2)
    (delCataleg B3)
    (delCataleg B4)
    (delCataleg B5)
    (delCataleg B6)
    (delCataleg B7)
    (delCataleg B8)
    (delCataleg B9)
    (delCataleg C0)
    (delCataleg C1)
    (delCataleg C2)
    (delCataleg C3)
    (delCataleg C4)
    (delCataleg C5)
    (delCataleg C6)
    (delCataleg C7)
    (delCataleg C8)
    (delCataleg C9)
    (delCataleg D0)
    (delCataleg D1)
    (delCataleg D2)
    (delCataleg D3)
    (delCataleg D4)
    (delCataleg D5)
    (delCataleg D6)
    (delCataleg D7)
    (delCataleg D8)
    (delCataleg D9)
    (delCataleg E0)
    (delCataleg E1)
    (delCataleg E2)
    (delCataleg E3)
    (delCataleg E4)
    (delCataleg E5)
    (delCataleg E6)
    (delCataleg E7)
    (delCataleg E8)
    (delCataleg E9)
    (delCataleg F0)
    (delCataleg F1)
    (delCataleg F2)
    (delCataleg F3)
    (delCataleg F4)
    (delCataleg F5)
    (delCataleg F6)
    (delCataleg F7)
    (delCataleg F8)
    (delCataleg F9)
    (delCataleg G0)
    (delCataleg G1)
    (delCataleg G2)
    (delCataleg G3)
    (delCataleg G4)
    (delCataleg G5)
    (delCataleg G6)
    (delCataleg G7)
    (delCataleg G8)
    (delCataleg G9)
    (delCataleg H0)
    (delCataleg H1)
    (delCataleg H2)
    (delCataleg H3)
    (delCataleg H4)

    (= (PaginesLlibre A0) 310)
    (= (PaginesLlibre A1) 356)
    (= (PaginesLlibre A2) 194)
    (= (PaginesLlibre A3) 416)
    (= (PaginesLlibre A4) 388)
    (= (PaginesLlibre A5) 263)
    (= (PaginesLlibre A6) 341)
    (= (PaginesLlibre A7) 425)
    (= (PaginesLlibre A8) 235)
    (= (PaginesLlibre A9) 219)
    (= (PaginesLlibre B0) 499)
    (= (PaginesLlibre B1) 304)
    (= (PaginesLlibre B2) 263)
    (= (PaginesLlibre B3) 146)
    (= (PaginesLlibre B4) 274)
    (= (PaginesLlibre B5) 183)
    (= (PaginesLlibre B6) 348)
    (= (PaginesLlibre B7) 541)
    (= (PaginesLlibre B8) 173)
    (= (PaginesLlibre B9) 314)
    (= (PaginesLlibre C0) 294)
    (= (PaginesLlibre C1) 358)
    (= (PaginesLlibre C2) 345)
    (= (PaginesLlibre C3) 162)
    (= (PaginesLlibre C4) 352)
    (= (PaginesLlibre C5) 203)
    (= (PaginesLlibre C6) 197)
    (= (PaginesLlibre C7) 432)
    (= (PaginesLlibre C8) 397)
    (= (PaginesLlibre C9) 149)
    (= (PaginesLlibre D0) 358)
    (= (PaginesLlibre D1) 340)
    (= (PaginesLlibre D2) 438)
    (= (PaginesLlibre D3) 304)
    (= (PaginesLlibre D4) 305)
    (= (PaginesLlibre D5) 150)
    (= (PaginesLlibre D6) 491)
    (= (PaginesLlibre D7) 391)
    (= (PaginesLlibre D8) 429)
    (= (PaginesLlibre D9) 289)
    (= (PaginesLlibre E0) 478)
    (= (PaginesLlibre E1) 371)
    (= (PaginesLlibre E2) 444)
    (= (PaginesLlibre E3) 232)
    (= (PaginesLlibre E4) 287)
    (= (PaginesLlibre E5) 339)
    (= (PaginesLlibre E6) 170)
    (= (PaginesLlibre E7) 373)
    (= (PaginesLlibre E8) 288)
    (= (PaginesLlibre E9) 433)
    (= (PaginesLlibre F0) 444)
    (= (PaginesLlibre F1) 617)
    (= (PaginesLlibre F2) 541)
    (= (PaginesLlibre F3) 330)
    (= (PaginesLlibre F4) 356)
    (= (PaginesLlibre F5) 413)
    (= (PaginesLlibre F6) 302)
    (= (PaginesLlibre F7) 294)
    (= (PaginesLlibre F8) 256)
    (= (PaginesLlibre F9) 488)
    (= (PaginesLlibre G0) 580)
    (= (PaginesLlibre G1) 334)
    (= (PaginesLlibre G2) 400)
    (= (PaginesLlibre G3) 196)
    (= (PaginesLlibre G4) 382)
    (= (PaginesLlibre G5) 415)
    (= (PaginesLlibre G6) 317)
    (= (PaginesLlibre G7) 157)
    (= (PaginesLlibre G8) 113)
    (= (PaginesLlibre G9) 491)
    (= (PaginesLlibre H0) 383)
    (= (PaginesLlibre H1) 396)
    (= (PaginesLlibre H2) 224)
    (= (PaginesLlibre H3) 353)
    (= (PaginesLlibre H4) 203)

    (predecessor H0 H4)
    (predecessor A3 B3)
    (predecessor E2 E8)
    (predecessor E1 E2)
    (predecessor F9 G7)
    (predecessor B9 E4)
    (predecessor G1 G4)
    (predecessor B3 H1)
    (predecessor E4 G6)
    (predecessor C9 F8)
    (predecessor B6 C9)
    (predecessor C8 D5)
    (predecessor B4 B8)
    (predecessor B5 C0)
    (predecessor B0 F8)
    (predecessor B3 G1)
    (predecessor A3 G3)
    (predecessor G6 H0)
    (predecessor E7 G8)
    (predecessor B0 E1)
    (predecessor A0 D3)
    (predecessor A1 F8)
    (predecessor D2 H2)
    (predecessor A2 B6)
    (predecessor G6 H3)
    (predecessor A7 E0)
    (predecessor G0 H4)
    (predecessor E0 F5)
    (predecessor A7 E3)
    (predecessor B6 D6)
    (predecessor A4 C8)
    (predecessor E5 H1)
    (predecessor F1 F2)
    (predecessor D8 E5)
    (predecessor A3 E4)
    (predecessor F6 G4)
    (predecessor F3 H3)
    (predecessor E1 H3)
    (predecessor H2 H4)
    (predecessor F1 G5)
    (predecessor C6 D2)
    (predecessor D5 F5)
    (predecessor F6 G9)
    (predecessor C3 E5)
    (predecessor F1 F3)
    (predecessor E1 E7)
    (predecessor C1 E2)
    (predecessor G9 H0)
    (predecessor C4 D8)
    (predecessor E6 G8)
    (predecessor B7 F8)
    (predecessor B0 F4)
    (predecessor F7 H0)
    (predecessor C7 H2)
    (predecessor G9 H2)
    (predecessor A9 B2)
    (predecessor G0 G4)

    (parallel G5 H4)
    (parallel B2 E2)
    (parallel A0 D7)
    (parallel G8 H0)
    (parallel A9 D8)
    (parallel A1 E2)

    (= (MesSeguent) 0)
    (= (PaginesMes) 0)
  )
  (:goal (forall (?ll) (imply (not (exists (?ll2) (predecessor ?ll ?ll2))) (llegit ?ll))))
)